### ISSUE TITLE
ODP API rte_get_timer_cycles() returns large value of cpu ticks to OFP which reset the TCP connection

### ISSUE THREAD

**Issue by manishmatey** [OpenDataPlane/odp#1030] opened 2020-09-08 10:11 UTC
OFP function tcp_ts_getticks() calls below ODP API's:

ofp_timer_ticks_u64(0) -> odp_timer_current_tick(shm->socket_timer_pool) -> rte_get_timer_cycles()

rte_get_timer_cycles() returns big value (in my case : 604475915736788 ) but tcp_ts_getticks() expect value between 0 to 1000 as per below comment  on function:
-------------------------------------------------------------------------------------------
/*
 * tcp_ts_getticks() in ms, should be 1ms < x < 1000ms according to RFC 1323.
 * We always use 1ms granularity independent of hz.
 */ 
static __inline uint32_t
tcp_ts_getticks(void)
{
    return (ofp_timer_ticks(0) * (OFP_TIMER_RESOLUTION_US / 1000));
}
----------------------------------------------------------------------------------------

Do we need to do any conversion here before sending back value to OFP? 
Is it a bug in ODP 1.23 ?

Please help me on this above issue.

**Comment by matiaselo** [comment] 2020-09-08 11:25
What looks suspicious to me is that `ofp_timer_ticks()` returns an integer, whereas `odp_timer_tick_to_ns()` returns `uint64_t`. Have you checked that there is no overflow?

**Comment by manishmatey** [comment] 2020-09-08 11:42
Hi @matiaselo ,

I have observed the overflow issue while moving on to version 1.21 and fixed it locally after changing integer to uint64_t. 
Here I am facing issue like OFP is expecting values between 1ms < x < 1000ms but rte_get_timer_cycles() is returning value which is very big (in my case : 604475915736788 ).  

How to convert this value to appropriate OFP value which is ranging from 1 to 1000 milisecond?

**Comment by matiaselo** [comment] 2020-09-08 12:18
Hi @manishmatey,

To me it looks like ODP-DPDK implementation is working according to the ODP spec. @JannePeltonen do you have any idea what the OFP code is trying to do here?

**Comment by JannePeltonen** [comment] 2020-09-08 12:32
I do not know that code but I would not be surprised if it were buggy. But this comment seems to be incorrect:
> tcp_ts_getticks() in ms, should be 1ms < x < 1000ms according to RFC 1323.

The RFC says that the clock resolution is between 1 ms and 1 s. Whoever wrote the comment may have meant the resolution but wrote the comment wrong.

**Comment by JannePeltonen** [comment] 2020-09-08 12:33
Since there is nothing wrong in ODP, I suppose we can close this ticket.

**Comment by manishmatey** [comment] 2020-09-08 14:21
Hi @JannePeltonen ,

Can you please help me to understand if rte_get_timer_cycles() returns big value (in my case : 604475915736788) but OFP expect value in millisecond.  Don't you feel any conversion needed here ?

I feel there is a conversation API is needed here as I am seeing TCP connection RESET immediately at the time of TCP handshake.

Is there any ODP API present which will convert the cpu cycles to millisecond ? 

Please guide me on this.

**Comment by JannePeltonen** [comment] 2020-09-08 15:58
As I said, I think the comment that you are referring to seems to be incorrect, i.e. the time stamps are not supposed to be between 1 and 1000 ms.

I do not know what is the problem. You probably have to debug it.

I am closing this issue since the problem is in OFP, not ODP.

**Closed by JannePeltonen** 2020-09-08 15:58 UTC
